fun main()
{
    print("student Enrollment No. : ")
    var enrollment = readLine()
    print("student Name : ")
    var name = readLine()
    print("student Branch : ")
    var branch = readLine()
    print("student Class : ")
    var Class = readLine()
    print("student Batch : ")
    var batch = readLine()
    print("student College Name : ")
    var clgName = readLine()
    print("student University Name : ")
    var uniName = readLine()
    print("student Age : ")
    var age = readLine()
    println()

    println("********************")
    println()
    println("Student's Data : ")
    println("Enrollment No. : $enrollment")
    println("Name : $name")
    println("Age : $age")
    println("Branch : $branch")
    println("Class : $Class")
    println("Batch : $batch")
    println("College Name : $clgName")
    println("University Name : $uniName")
}